// WACP THAT TAKES THE NAME OF THE DAY FROM THE USER AS AN INPUT AND DISPLAYS THE NEXT TWO DAYS OF THE WEEK. THE DAY SHOULD BE REPRESENTED USING AN ENUM.THE PROGRAM MUST HANDLE INVALID DAY NAMES AND SHOULD CORRECTLY CYCLE FROM SUNDAY BACK TO MONDAY. 
#include <stdio.h>
